apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - service-account.yaml
  - deployment.yaml
  - service.yaml
labels:
  - pairs:
      app.kubernetes.io/name: vaipex-demo
      app.kubernetes.io/part-of: vaipex-gitops-delivery-control-plane
      app.kubernetes.io/managed-by: argocd
    includeSelectors: true
