apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: apps-dev
resources:
  - ../../base
labels:
  - pairs:
      vaipex.io/environment: development
images:
  - name: docker.io/traefik/whoami
    newName: docker.io/traefik/whoami
    digest: sha256:c4717a8d1f0134a7444e24f881160e033991f23027c6c5a9a3f8fd22e70d1d44
